### ISSUE TITLE
Live TV only fills 75% of TV

### ISSUE THREAD

**Issue by maverickme** [pipelka/roboTV#31] opened 2016-12-03 19:34 UTC
On my SonyKD65ZD9 TV I have the following problem.

The picture of the Live TV does not fill the complete TV.

At recording replay, everything is fine

here's an example picture

![bild](https://cloud.githubusercontent.com/assets/3810007/20861674/1fec276c-b996-11e6-9882-bb04412f2f1f.jpg)

1/4 of the screen is black and the rest of the image is displayed on the left side.

I have tried the following versions:

vdr plugin - roboTV
0.9.100 - 0.5.1
0.9.101 - 0.5.2
0.9.102 - 0.6.0
git fe4405f - git 597cb4b

**Comment by pipelka** [comment] 2016-12-04 12:39
Very strange. Nice TV, btw, ...

Does this happen with all channels ?
Do other Live Channel providers (e.g. Google Play Movies) work fine ?

Please post the VDR log output when tuning the channel. Should look like this:
<pre>
Dec  4 13:25:03 darth vdr: [13567] roboTV: Found available device 1
Dec  4 13:25:03 darth vdr: [13567] roboTV: Channel information found in cache
Dec  4 13:25:03 darth vdr: [13567] roboTV: Creating demuxers
Dec  4 13:25:03 darth vdr: [13567] roboTV: Stream: H264 PID: 100 1920x1080 DAR: 1,78 FPS: 25,000 SPS/PPS/VPS: 21/15/0 bytes (parsed: yes)
Dec  4 13:25:03 darth vdr: [13567] roboTV: Stream: AC3 PID: 110 48000 Hz, 2 channels, Lang: deu (parsed: yes)
Dec  4 13:25:03 darth vdr: [13567] roboTV: Successfully switched to channel 41 - RTL HD Austria
Dec  4 13:25:03 darth vdr: [13567] DVBAPI: 0.0 set CAM decrypt (SID 11911 (0x2E87), caLm 4, HasCaDescriptors 1)
Dec  4 13:25:03 darth vdr: [13567] roboTV: device attached to receiver
Dec  4 13:25:03 darth vdr: [13567] roboTV: done switching.
Dec  4 13:25:03 darth vdr: [13567] roboTV: --------------------------------------
Dec  4 13:25:03 darth vdr: [13567] roboTV: Started streaming of channel RTL HD Austria (priority 50)
</pre>

**Comment by maverickme** [comment] 2016-12-04 13:42
Yes! With the channels I've tested around (~ 50 of 300)
Google Play : I still have to test!

VDR Log:
> Dec  3 12:46:15 server vdr: [19551] roboTV: stream change requested
> Dec  3 12:46:15 server vdr: [19551] roboTV: demuxers ready
> Dec  3 12:46:15 server vdr: [19551] roboTV: Stream: DVBSUB PID: 6650 Lang: deu (parsed: yes)
> Dec  3 12:46:15 server vdr: [19551] roboTV: Stream: H264 PID: 6651 1920x1080 DAR: 1,78 FPS: 25,000 SPS/PPS/VPS: 25/4/0 bytes (parsed: yes)
> Dec  3 12:46:15 server vdr: [19551] roboTV: Stream: AC3 PID: 6652 48000 Hz, 2 channels, Lang: deu (parsed: yes)
> Dec  3 12:46:15 server vdr: [19551] roboTV: create streamchange packet
> Dec  3 12:46:15 server vdr: [19551] roboTV: got first key frame
> Dec  3 12:46:15 server vdr: [19551] roboTV: found new PMT version (0)
> Dec  3 12:46:15 server vdr: [19551] roboTV: updating demuxers
> Dec  3 12:46:15 server vdr: [19551] roboTV: Stream: DVBSUB PID: 6650 Lang: deu (parsed: yes)
> Dec  3 12:46:15 server vdr: [19551] roboTV: Stream: H264 PID: 6651 0x0 DAR: 0,00 FPS: 0,000 SPS/PPS/VPS: 0/0/0 bytes (parsed: no)
> Dec  3 12:46:15 server vdr: [19551] roboTV: Stream: AC3 PID: 6652 0 Hz, 0 channels, Lang: deu (parsed: no)
> Dec  3 12:46:15 server vdr: [19551] roboTV: --------------------------------------
> Dec  3 12:46:15 server vdr: [19551] roboTV: NEW AUDIO INFORMATION:
> Dec  3 12:46:15 server vdr: [19551] roboTV: Channels: 6
> Dec  3 12:46:15 server vdr: [19551] roboTV: Samplerate: 48000 Hz
> Dec  3 12:46:15 server vdr: [19551] roboTV: Bitrate: 384000 bps
> Dec  3 12:46:15 server vdr: [19551] roboTV: --------------------------------------
> Dec  3 12:46:15 server vdr: [19551] roboTV: stream change requested
> Dec  3 12:46:15 server vdr: [19551] roboTV: --------------------------------------
> Dec  3 12:46:15 server vdr: [19551] roboTV: NEW PICTURE INFORMATION:
> Dec  3 12:46:15 server vdr: [19551] roboTV: Picture Width: 1920
> Dec  3 12:46:15 server vdr: [19551] roboTV: Picture Height: 1080
> Dec  3 12:46:15 server vdr: [19551] roboTV: Display Aspect Ratio: 1,78
> Dec  3 12:46:15 server vdr: [19551] roboTV: Frames per second: 25,00
> Dec  3 12:46:15 server vdr: [19551] roboTV: --------------------------------------
> Dec  3 12:46:15 server vdr: [19551] roboTV: stream change requested

**Comment by pipelka** [comment] 2016-12-04 15:11
OK. The log snipped is from playing a recording. I just want to be sure that the aspect ratio
of the tuned live channel is ok. Please post a snippet from tuning a live channel.

**Comment by pipelka** [comment] 2016-12-04 15:28
Another question that jumped into my mind:
does the EPG view cover the whole screen area ?

**Comment by maverickme** [comment] 2016-12-04 16:24
new Log: http://pastebin.com/ddiFcA66
EPG View  works in fullscreen

**Comment by maverickme** [comment] 2016-12-05 07:49
I tested live channel provider Google Play and its also fullscreen

**Comment by pipelka** [comment] 2016-12-05 07:57
Ok. Now we can exclude some weird Live Channels and / or TV issues.
It would be great to get a log from your TV when starting playback.

Is it possible for you to grab the log via "adb logcat" ?

**Comment by maverickme** [comment] 2016-12-05 19:17
logcat: http://pastebin.com/3Lm03DLT

But the only version with which I get a picture at all is 0.5.0 with all of the later versions the TV remains black, and open EPG or open records the app crashes

**Comment by pipelka** [comment] 2016-12-05 19:38
Hmm, ...
Ok. Let's recap:
* only version 0.5.0 starts - with a distorted picture
* all other versions crash

Please build the version from "master" (roboTV and VDR plugin) and post the log from the crash.
I thought the distorted picture is a problem of all the versions you mentioned. But obviously newer versions crash. We need to fix this issue on "master".

**Comment by pipelka** [comment] 2016-12-05 19:54
One more question.
Which Android version has your TV ?

**Comment by maverickme** [comment] 2016-12-06 18:55
The current git version crashed only once time after channel import, recordings works!
EPG does not work!
Live TV same as in Version 0.5.0 Picture in 4:3 Format at the left side.

VDR log:
> Dec  6 19:41:57 server vdr: [7466] roboTV: Preferred language: deu,ger / type: 0
> Dec  6 19:41:57 server vdr: [7466] roboTV: device detached
> Dec  6 19:41:57 server vdr: [7466] roboTV: LiveQueue terminated
> Dec  6 19:41:57 server vdr: [7466] roboTV: live streamer terminated
> Dec  6 19:41:57 server vdr: [7466] roboTV: Found available device 1
> Dec  6 19:41:57 server vdr: [7466] roboTV: Channel information found in cache
> Dec  6 19:41:57 server vdr: [7466] roboTV: Creating demuxers
> Dec  6 19:41:57 server vdr: [7466] roboTV: Stream: H264 PID: 6110 1280x720 DAR: 1,78 FPS: 50,000 SPS/PPS/VPS: 24/4/0 bytes (parsed: yes)
> Dec  6 19:41:57 server vdr: [7466] roboTV: Stream: AC3 PID: 6120 48000 Hz, 2 channels, Lang: deu (parsed: yes)
> Dec  6 19:41:57 server vdr: [7466] roboTV: Stream: AC3 PID: 6121 48000 Hz, 2 channels, Lang: mis (parsed: yes)
> Dec  6 19:41:57 server vdr: [7466] roboTV: Stream: AC3 PID: 6123 48000 Hz, 2 channels, Lang: mul (parsed: yes)
> Dec  6 19:41:57 server vdr: [7466] roboTV: Stream: DVBSUB PID: 6131 Lang: deu (parsed: yes)
> Dec  6 19:41:57 server vdr: [7466] roboTV: Successfully switched to channel 2 - ZDF HD
> Dec  6 19:41:57 server vdr: [7466] roboTV: device attached to receiver
> Dec  6 19:41:57 server vdr: [7466] roboTV: done switching.
> Dec  6 19:41:57 server vdr: [7466] roboTV: --------------------------------------
> Dec  6 19:41:57 server vdr: [7466] roboTV: Started streaming of channel ZDF HD (priority 50)
> Dec  6 19:41:57 server vdr: [7839] roboTV: stream change notification

TV catlog: http://pastebin.com/kzHZXAHr

TV Android Version: 6.0.1

**Comment by pipelka** [comment] 2016-12-06 19:11
If it's possible I would like to see a log of every crash that happens.
What means "EPG does not work" exactly. What happens, what's the error message, ...

From the logs I see that the TV view spans a layout of 1440x1080:
<pre>
12-06 19:41:54.477: D/Tvx-TvPlayer(3623): [TunableTvView] TvView.layout(left=0, top=0, right=1920, bottom=1080)
12-06 19:41:54.485: D/Tvx-TvPlayer(3623): [TunableTvView] onTrackSelected(inputId=org.xvdr.robotv/.service.RoboTvInputService, type=1, trackId=6110)
12-06 19:41:54.485: D/Tvx-TvPlayer(3623): [TunableTvView] TvView.getTracks(type=1): returns [android.media.tv.TvTrackInfo@5d0dab5]
12-06 19:41:54.485: D/Tvx-TvPlayer(3623): [TunableTvView] TvView.setX(x=0.0)
12-06 19:41:54.485: D/Tvx-TvPlayer(3623): [TunableTvView] TvView.setLayoutParams(leftMargin=240, rightMargin=0, topMargin=0, bottomMargin=0, gravity=0x800003, width=1440, height=1080)
</pre>

The question is: Why ?

Thanks. I'll walk through the log and check what could be wrong, ...

BTW, populating the EPG takes a couple of minutes (depends on the number of channels), ...

**Comment by pipelka** [comment] 2016-12-06 19:51
Please check if the "aspect" branch makes any difference for you:
https://github.com/pipelka/roboTV/commits/aspect

It also logs the video size and aspect ratio.

**Comment by maverickme** [comment] 2016-12-08 20:29
For further logs I had these days still no time.

But the new version I have already tested (no change).

What is strange in the channelsettings (hide channels) the live tv in the background is screen filling, normal live TV are already only the 75% at the left side

Further logs and tests I can make at the weekend

PS. The VDR log 2 days ago was the wrong to the catlog, the channel was switched to the "Sport1 HD" which really has this 1440x1080 resolution

At the weekend I can do more

**Comment by pipelka** [comment] 2016-12-09 14:16
I think I've found something.

I've been able to reproduce the behaviour by manually setting a 4:3 layout of the tv view:
![20161209_150015](https://cloud.githubusercontent.com/assets/584386/21051792/195a268e-be22-11e6-967e-c25f0444a80d.jpg)

Maybe the TV view is not spawning the whole view on your device. 
Please check 97083d8fa0a63ea3346273d0a762f0318fcf7439

**Comment by maverickme** [comment] 2016-12-11 13:22
I have now again tested with the last git version of the app and the plugin
Here the logs

Chrash after channelimport vdr -plugin http://pastebin.com/b3tH7TTq
Chrash after channelimport  http://pastebin.com/aiPMPDXT

Crash Streamingchannels robotv Settings http://pastebin.com/RVmfWZKj
Crash Streamingchannels robotv Settings Screenshot http://www.bilder-upload.eu/show.php?file=546c8d-1481461979.png

hide channels robotv ard - zdf switch vdr-plugin http://pastebin.com/yR5C1y4K
hide channels robotv ard - zdf switch http://pastebin.com/bAAiVvNx

hide channels robotv zdf - kabel 1 switch vdr-plugin http://pastebin.com/jynGE5uU
hide channels robotv zdf - kabel 1 switch http://pastebin.com/GTFTtQ7D

live TV robotv kabel 1 - sat 1 switch vdr plugin http://pastebin.com/Y99Y9es5
live TV robotv kabel 1 - sat 1 switch http://pastebin.com/8JU048yw

live TV robotv sat1 - ard switch vdr plugin http://pastebin.com/fL6QWkBJ
Live TV robotv sat1 - ard switch http://pastebin.com/e58tUVCq

**Comment by maverickme** [comment] 2016-12-11 13:35
Just I had something strange, I switched to ARD (again only 4: 3 picture) went out of the room and when I came back the picture was screenfilled, but unfortunately I have no log of the period.

I will try to provoke this again. If i success, i will try to log it.

**Comment by pipelka** [comment] 2016-12-11 14:03
Thanks for the brief logging information.

Hopefully the crash on importing the channels should be fixed with: 0cb50cf2303ba32db9b8a5316a07bef6d6ea3fc6
The crash on streamingchannels settings is caused by opening an activity that isn't part on the specification anymore. To prevent this i could add a dummy activity.

The logs from switching channels do not give a clue. Everything seems correct, ...

**Comment by maverickme** [comment] 2016-12-14 20:23
Importing channels is fixed, thanks!

The mail problem solved after install/update https://play.google.com/store/apps/details?id=com.google.android.tv app

Now all channels are screenfilled. Thanks.

**Comment by pipelka** [comment] 2016-12-14 20:38
Great. I'm really glad that it's working now for you.
The good thing is that I now know how to scale the live tv view on the screen ;-)

**Closed as completed by pipelka** 2016-12-14 20:38 UTC
