### ISSUE TITLE
Stream stops for 1 second with a blue circle in the middle of the screen. 

### ISSUE THREAD

**Issue by tunip** [pipelka/roboTV#7] opened 2016-02-05 10:09 UTC
Now I switched from Kodi/Tvheadend to roboTV/VDR on my SHIELD TV.

I use roboTV now sice ~1 week and have one small issue.
After round about 30-60 minutes I see the "blue circle" in the middle of the screen and the stream stops (pause) for ~1 second. This happens frequntly.

I try to collect some logs when the issue happens next time...

vdr (2.2.0) 
xvdr (0.9.9 roboTV branch)
roboTV (Pre-release) 0.1.0 from your github repo

Many thanks for your effort and the great app!

**Comment by pipelka** [comment] 2016-02-05 16:53
It's rebuffering data from the server.

Are you connected via WiFi or ethernet ?
On an ethernet connection this happens for me sometimes but not frequently. Maybe it's caused by some heavy network traffic. I installed some traffic-shaping rules on my server giving the video packets a dedicated bandwidth.

There are also some issues with the Shield TV on Android L. Hopefully the situation will get better on Android M (to be released soon, ... maybe).

I will release a 0.2.0 version today or tomorrow addressing some audio / video sync problems.

**Comment by tunip** [comment] 2016-02-08 12:22
SHIELD TV and VDR server connected over gigabit-ethernet. If i copy a testfile from the fileserver (same system) to the SHIELD TV i have a transferrate of ~80Mbps (9,9 MB/s) which should be suffcient. If I watch TV no other taffic is on the network. I will try some QoS rules on the switch. On the last footballmatch I had it only one time. Not really a big issue. Hope on Android M for SHIELD TV we see some improvements.

**Comment by tunip** [comment] 2016-02-22 17:13
Android M is out now for Shield TV. I will observe and report next days if the upgrade helps.

**Comment by pipelka** [comment] 2016-02-23 08:19
There's still the same issue on Android M. I had to add a workaround for the following unresolved bug:
Playback of 1080i channels starts to stutter badly after about ~15 minutes. This doesn't happen on 720p channels.
The workaround is to completely reset the decoder. This can cause playback glitches and rebuffering. I''m further investigating on that, ...

**Comment by pipelka** [comment] 2016-03-13 12:44
I'm pretty sure the blue circle is gone in the 0.4.0 release (for obvious reasons). Unfortunately i had to keep the Shield TV workaround (now I'm pretty sure it's an ExoPlayer issue). I should assemble some testvideos and report this issue upstream.

**Comment by tunip** [comment] 2016-07-11 10:24
Maybe libvlc is an alternative player instead of exoplayer.

**Comment by pipelka** [comment] 2016-07-11 10:43
I'm thinking about writing my own player based on MediaCodec and MediaSync. It would only implement the things I need (and of course will be much faster, better, ..) ;-)
To be honest I already have the skeleton of the player but it needs a bit more time, ...

**Comment by pipelka** [comment] 2016-07-12 20:49
Until the new player infrastructure is in place version 0.5.1 should perform much better on the Shield TV (with upgrade 3.2)

**Comment by pipelka** [comment] 2016-09-24 07:23
Is this really still an issue ?

**Comment by tunip** [comment] 2016-09-24 08:46
Never seen this a long time.

**Comment by pipelka** [comment] 2016-09-24 09:45
Same for me here. Closing.

**Closed as completed by pipelka** 2016-09-24 09:45 UTC
Labels: question
